// ============================================================
//  KÉRDÉSEK SZERKESZTÉSE
//  Ide másold be a kérdéseket az alábbi formátumban.
//  Minden kérdés egy számozott sorral kezdődik:
//
//  1. kérdés / Fråga 1
//  SV: [svéd kérdés]
//  HU: [magyar kérdés]
//  Svenska: [svéd válasz]
//  Magyar: [magyar válasz]
//
//  A kvíz válaszlehetőségek automatikusan generálódnak.
// ============================================================

var QUESTIONS_TEXT = `
1. kérdés / Fråga 1
SV: Vad ingår i det som brukar kallas för ellagstiftningen?
HU: Mi tartozik az úgynevezett elektromos jogszabályok körébe?
Svenska: Ellagstiftningen består av de lagar, förordningar och föreskrifter som gäller elektriska anläggningar och som har beslutats av riksdag, regering eller utsedda myndigheter. Dessa bestämmelser är vi skyldiga att följa och ofta är de straffsanktionerade och man kan dömas till ansvar om man bryter mot dessa. Svensk standard ingår inte i ellagstiftningen.
Magyar: Az elektromos jogszabályok azokat a törvényeket, rendeleteket és előírásokat foglalják magukban, amelyek az elektromos berendezésekre vonatkoznak, és amelyeket az országgyűlés, a kormány vagy a kijelölt hatóságok fogadtak el. Ezeket kötelező betartani, és általában szankcionáltak – megszegésük büntetőjogi következményekkel járhat. A svéd szabvány nem része az elektromos jogszabályoknak.

2. kérdés / Fråga 2
SV: Vilka myndigheter finns inom elområdet?
HU: Mely hatóságok működnek a villamos energia területén?
Svenska: Inom ellagstiftningen brukar man tala om fyra myndigheter. Elsäkerhetsverket är förvaltningsmyndighet och tillsynsmyndighet. Energimarknadsinspektionen (EMI) är nätmyndighet. Svenska Kraftnät (SvK) är systemansvarig myndighet och ansvarar för stamnätet. Svenska Kraftnät är även elberedskapsmyndighet.
Magyar: Az elektromos jogszabályok terén négy hatóságot szoktak megemlíteni. Az Elsäkerhetsverket közigazgatási és felügyeleti hatóság. Az Energimarknadsinspektionen (EMI) hálózati hatóság, amely hálózati koncessziókat engedélyez és a díjak méltányosságát vizsgálja. A Svenska Kraftnät (SvK) rendszerirányító hatóság, amely az egyensúlyt felügyeli és a gerincvezetéket üzemelteti. A Svenska Kraftnät egyúttal az elektromos ellátás védelméért felelős hatóság is.

3. kérdés / Fråga 3
SV: Vilka elinstallationsarbeten kräver behörighet?
HU: Mely villamossági munkák igényelnek jogosítványt?
Svenska: Det är elinstallatörsförordningen som reglerar vilka arbeten som kräver formell behörighet. Elinstallationsarbete som avser utförande, ändring eller reparation av en elektrisk starkströmsanläggning ska utföras av elinstallatör eller av yrkesman under överinseende av elinstallatör. Följande får utföras utan behörighet: 1) Utbyte av elkopplare och anslutningsdon för högst 16 A, 400 V. 2) Utbyte av ljusarmatur i torra icke brandfarliga utrymmen inne i bostäder. 3) Utförande av starkströmsanläggning i skyddsklenspänningskrets max 50 V, max 200 VA, säkring max 10 A. 4) Förläggning av värmekabel för skyddsklenspänning max 50 V. 5) Losskoppling eller anslutning av anordning i laboratorium eller provrum.
Magyar: A villamosszerelői rendelet határozza meg, mely munkák igényelnek formális jogosítványt. Az erős áramú berendezések kivitelezésével, módosításával vagy javításával kapcsolatos munkát engedéllyel rendelkező villanyszerelőnek vagy annak felügyelete alatt dolgozó szakembernek kell elvégeznie. Jogosítvány nélkül végezhető: 1) Legfeljebb 16 A, 400 V-os kapcsolók és csatlakozók cseréje. 2) Lámpatestek cseréje száraz, nem tűzveszélyes lakáshelyiségekben. 3) Legfeljebb 50 V / 200 VA / 10 A biztosítójú SELV-körbe tartozó berendezés kivitelezése. 4) Legfeljebb 50 V-os védő kisfeszültségű fűtőkábel fektetése. 5) Berendezés leválasztása vagy csatlakoztatása laboratóriumban vagy kísérleti szobában.

4. kérdés / Fråga 4
SV: Vad menas med elinstallatör?
HU: Mit jelent a villamosszerelő (elinstallatör) fogalma?
Svenska: Elinstallatör är en person som av Elsäkerhetsverket meddelats behörighet att i en angiven omfattning utföra elinstallationsarbete. Det finns flera nivåer på behörighet. Ansvaret är personligt och ett företag kan inte inneha behörighet. (2§, Elinstallatörsförordning SFS 1990:806)
Magyar: A villamosszerelő olyan személy, akinek az Elsäkerhetsverket meghatározott körű villamossági munkák elvégzésére jogosítványt adott ki. A jogosítványnak több szintje létezik. A felelősség személyes – egy vállalkozás nem rendelkezhet jogosítvánnyal. (2§, Elinstallatörsförordning SFS 1990:806)

5. kérdés / Fråga 5
SV: Vad menas med yrkesman?
HU: Mit jelent a szakember (yrkesman) fogalma?
Svenska: För närvarande finns inga formella krav på den som elinstallatörsförordningen kallar yrkesman. Det är elinstallatören som ska se till att yrkesmannen har de kunskaper och färdigheter som arbetet kräver och som avgör vem som får arbeta under hans överinseende. Kompetenskravet blir helt beroende på installationsarbetets komplexitet. Yrkesman behöver inte innebära en yrkesutbildad elektriker.
Magyar: Jelenleg nincsenek formális követelmények a villamosszerelői rendelet által szakembernek nevezett személy számára. A villamosszerelő feladata biztosítani, hogy a szakember rendelkezzen a munkához szükséges tudással és készségekkel, és ő dönti el, ki dolgozhat a felügyelete alatt. A kompetenciaigény teljesen a munka összetettségétől függ. A szakember tehát nem feltétlenül jelent szakképzett villanyszakembert.

6. kérdés / Fråga 6
SV: Vad är en anordning?
HU: Mi a berendezés (anordning)?
Svenska: Med elektrisk anordning avses elektrisk utrustning där el används och som är avsedd att anslutas till en starkströmsanläggning. Det kan vara utrustning för användning av el, t.ex. tvättmaskiner, övriga maskiner, belysningsarmaturer och värmeapparater. (2§, Starkströmsförordning SFS 2009:22)
Magyar: Az elektromos berendezés olyan elektromos felszerelés, amelyben az elektromosságot felhasználják, és amelyet erős áramú hálózatra való csatlakoztatásra szánnak. Lehet például mosógép, egyéb gép, világítótest vagy fűtőkészülék. (2§, Starkströmsförordning SFS 2009:22)

7. kérdés / Fråga 7
SV: Vilka elarbeten kräver inte behörighet?
HU: Mely villamossági munkák nem igényelnek jogosítványt?
Svenska: Det är endast elinstallationsarbete som avser starkströmsanläggningar som kräver behörighet. Normala skötselåtgärder såsom byte av säkringar och manövrering av brytare kräver ingen behörighet. Generellt får man utföra, reparera och ändra CE-märkt elektrisk materiel såsom kopplingsutrustningar och belysningsarmaturer utan krav på behörighet. Det är den som utför arbetet som är ansvarig för att arbetet kontrolleras.
Magyar: Csak az erős áramú berendezésekre irányuló villamossági munkák igényelnek jogosítványt. Normális karbantartási intézkedések – például biztosítók cseréje, megszakítók működtetése és védőkészülékek visszaállítása – nem igényelnek jogosítványt. Általános szabályként CE-jelöléssel ellátott villamos anyagok – pl. kapcsolókészülékek és lámpatestek – javítása és módosítása jogosítvány nélkül is elvégezhető. A munkát végző felel az ellenőrzésért.

8. kérdés / Fråga 8
SV: Är det behörighetskrävande att reparera elutrustning på en maskin?
HU: Igényel-e jogosítványt egy gép elektromos berendezésének javítása?
Svenska: Nej. Det finns inga formella krav på behörighet för att utföra, reparera eller ändra elutrustningar tillhörande maskiner. (Se även fråga 7.)
Magyar: Nem. Nincsenek formális jogosítványkövetelmények a gépek elektromos berendezéseinek kivitelezéséhez, javításához vagy módosításához. (Lásd még a 7. kérdést.)

9. kérdés / Fråga 9
SV: Hur vet man vad som är maskin respektive elektrisk anläggning?
HU: Hogyan lehet megkülönböztetni a gépet az elektromos berendezéstől?
Svenska: En maskin ska vara CE-märkt och av maskinens dokumentation framgår dess anslutningspunkt. I många fall är det ganska tydligt då maskinen ansluts till anläggningen med en flexibel kabel. I andra fall kan det vara svårare, t.ex. för pappersmaskiner. Hissanläggningar i sin helhet är normalt maskiner men servicebelysning och uttag i hisschakt kan tillhöra den elektriska anläggningen.
Magyar: A gépnek CE-jelöléssel kell rendelkeznie, és dokumentációja megjelöli a csatlakozási pontot. Sok esetben ez egyértelmű, mivel a gép rugalmas kábellel csatlakozik a hálózathoz. Más esetekben – például papírgyártó gépeknél – nehezebb az elhatárolás. A liftberendezések egésze általában gépnek minősül, de a liftakna szervizvilágítása és konnektorai a villamos berendezéshez tartozhatnak.

10. kérdés / Fråga 10
SV: Kan man utföra ett installationsarbete trots att man inte har behörighet och sedan be en elinstallatör besiktiga och stå som ansvarig för installationen?
HU: Elvégezhet-e valaki telepítési munkát jogosítvány nélkül, és kérhet-e aztán egy villamosszerelőtől felülvizsgálatot és felelősségvállalást?
Svenska: Nej. Den yrkesman som utför installationsarbetet ska vara anställd i samma företag som elinstallatören. Om man inte har egen behörighet och inte utför installationsarbetet inom de regler som gäller för anställningsförhållande med en elinstallatör kan detta vara brottsligt och man kan dömas till böter eller fängelse i upp till ett år. (6§, Elinstallatörsförordning SFS 1990:806)
Magyar: Nem. A telepítési munkát végző szakembernek ugyanannál a vállalkozásnál kell alkalmazásban állnia, mint a villamosszerelőnek. Ha valaki nem rendelkezik saját jogosítvánnyal, és nem alkalmazzák a villamosszerelővel fennálló munkaszerződésre vonatkozó szabályok keretein belül, ez bűncselekménynek minősülhet, és pénzbírsággal vagy akár egy évig terjedő szabadságvesztéssel büntethető. (6§, Elinstallatörsförordning SFS 1990:806)

11. kérdés / Fråga 11
SV: Vem är ansvarig för en elektrisk anläggning?
Svenska: Enligt starkströmsförordningen är det innehavaren som ska se till att elektriska anläggningar och anslutna anordningar fortlöpande kontrolleras så att de ger betryggande säkerhet mot person- eller sakskada. Innehavare är inte definierat men kan sägas vara den som faktiskt innehar en anläggning oavsett om innehavet grundar sig på äganderätt eller nyttjanderätt. Om ägare och nyttjare är olika personer kan ett avtal reglera vem som svarar för kontroll och åtgärder. (4§, Starkströmsförordning SFS 2009:22)
HU: Ki felelős egy villamos berendezésért?
Magyar: Az erős áramú berendezésekre vonatkozó rendelet szerint az üzemeltető köteles gondoskodni arról, hogy a villamos berendezéseket és a csatlakoztatott készülékeket folyamatosan ellenőrizzék, és azok megbízható védelmet nyújtsanak személyi sérülés és anyagi kár ellen. Az üzemeltető fogalma nincs pontosan meghatározva, de általában az a személy tekinthető annak, aki ténylegesen üzemeltet egy berendezést – függetlenül attól, hogy az tulajdonjogon vagy használati jogon alapul. Ha a tulajdonos és a használó különböző személy, szerződésben rendelkezhetnek arról, ki felel az ellenőrzésért és az intézkedésekért. (4§, Starkströmsförordning SFS 2009:22)

12. kérdés / Fråga 12
SV: Vad måste jag som arbetsgivare tänka på om jag har personal som ska utföra enklare åtgärder och elarbeten?
Svenska: Det är i första hand tre områden som man måste beakta: om arbetet kräver formell behörighet, elsäkerheten för de personer som deltar i arbetet, samt att installationsarbetet utförs på rätt sätt och kontrolleras i betryggande omfattning. Om arbetet är behörighetskrävande ska det utföras av elinstallatör med tillräcklig behörighet eller av yrkesman anställd i samma företag – man kan normalt inte "låna in" en behörig installatör. Vid arbete där det finns elektrisk fara måste reglerna om elsäkerhet vid arbete beaktas, bl.a. riskbedömning, elsäkerhetsplanering och skyddsåtgärder. Arbetet kan även behöva kontrolleras innan idrifttagning.
HU: Mire kell figyelnem munkáltatóként, ha van olyan személyzetem, amely egyszerűbb villamos munkákat végez?
Magyar: Elsősorban három területet kell figyelembe venni: hogy a munka igényel-e formális jogosítványt, a munkában részt vevők elektromos biztonsága, valamint hogy a telepítési munkát helyesen végzik-e és megfelelően ellenőrzik-e. Ha a munka jogosítványköteles, azt elegendő jogosítvánnyal rendelkező villanyszerelőnek vagy az ugyanazon vállalkozásnál alkalmazott szakembernek kell elvégeznie – általában nem lehet "kölcsönkérni" egy jogosult villanyszerelőt. Elektromos veszéllyel járó munkánál be kell tartani az elektromos biztonsági előírásokat, beleértve a kockázatértékelést, a biztonsági tervezést és a védőintézkedéseket. A munkát az üzembe helyezés előtt esetleg ellenőrizni is kell.

13. kérdés / Fråga 13
SV: Vi har fått i uppdrag att elektrifiera ett garage som står på en annan fastighet än den som vi ska ta elen ifrån. Det är samma ägare av fastigheterna. Får man ta ut el från en fastighet och föra över till en annan fastighet?
Svenska: Reglerna om rätten att bygga en ledning finns i ellagens bestämmelser om nätkoncession. Generellt krävs ett tillstånd men regeringen har givit ut en förordning om undantag, SFS 2007:215. Alla ledningar inom eller på en byggnad är undantagna från kravet på tillstånd. Enligt sjätte paragrafen får ett internt nät – som överför el till anläggningar i omedelbar närhet till ett bostadshus – byggas utan nätkoncession, om elen används för egen räkning. Om fastighetsägaren avser att hyra ut garaget torde ledningen inte få byggas utan att garaget har ett eget abonnemang. Det väsentliga är att garaget ligger i omedelbar närhet till ett bostadshus. Det är Energimarknadsinspektionen som handlägger ärenden om koncession. (SFS 2007:215)
HU: Megbíztak minket egy garázs villamosításával, amely más telken áll, mint ahonnan az áramot vesszük. Ugyanaz a tulajdonos. Szabad-e egyik telekről a másikra áramot átvezetni?
Magyar: A villamosvezetékek építési jogára vonatkozó szabályok az elektromos törvény hálózati koncesszióra vonatkozó rendelkezéseiben találhatók. Általában engedély szükséges, de a kormány kiadott egy kivételekről szóló rendeletet (SFS 2007:215). Az épületen belüli vagy azon lévő összes vezeték mentesül az engedélyezési kötelezettség alól. A rendelet 6. §-a szerint belső hálózat – amely lakóház közvetlen közelében lévő épületbe vezet áramot – engedély nélkül is kiépíthető, ha az áramot saját célra használják. Ha a tulajdonos bérbe kívánja adni a garázsát, a vezeték valószínűleg nem építhető meg – a garázsnak saját előfizetéssel kell rendelkeznie. A lényeg az, hogy a garázs a lakóház közvetlen közelében legyen. A koncessziós ügyeket az Energimarknadsinspektionen intézi. (SFS 2007:215)

14. kérdés / Fråga 14
SV: Enligt Elsäkerhetsverkets föreskrifter ska uttag antingen vara försedda med petskydd eller utföras eller placeras så att risken för barnolycksfall begränsas. Var finner man anvisningar om hur man utför eller placerar uttag för att åstadkomma skydd mot barnolycksfall?
Svenska: Elinstallationsreglerna går längre vad gäller barnsäkerhet än vad föreskrifterna gör. I bilaga 41A, punkt 2.6, finns anvisningar om hur man kan begränsa risken för barnolycksfall om uttag saknar petskydd: placeras minst 1,7 m över golv eller mark, är skyddade av fast inredning eller stationär utrustning såsom spis eller kylskåp, är blockerade, är försedda med låsbart lock, eller är skyddade på annat sätt.
HU: Az Elsäkerhetsverket előírásai szerint a konnektorokat vagy petákáló (gyermekvédő) eszközzel kell ellátni, vagy úgy kell elhelyezni, hogy a gyermekbalesetek kockázata csökkentett legyen. Hol találhatók erre vonatkozó útmutatások?
Magyar: A telepítési szabályok messzebb mennek a gyermekbiztonság terén, mint az előírások. A 41A melléklet 2.6. pontja útmutatást ad arra, hogyan csökkenthető a gyermekbalesetek kockázata petákáló nélküli konnektorok esetén: legalább 1,7 m magasságban helyezzék el a padló vagy a talaj felett, rögzített berendezéssel (pl. tűzhely vagy hűtőszekrény) védjék, blokkoltak legyenek, zárható fedéllel legyenek ellátva, vagy más módon legyenek védve.

15. kérdés / Fråga 15
SV: Måste man CE-märka en elcentral?
Svenska: När elcentralen kan köpas som funktionell enhet är den en produkt som ska utföras enligt förordningen (1993:1068) om elektrisk materiel och Elsäkerhetsverkets föreskrifter (ELSÄK-FS 2000:1). Tillverkaren ska utarbeta en teknisk dokumentation och EG-försäkran samt förse elcentralen med CE-märke. När elcentralen platsbyggs och ingår i den färdiga anläggningen (fast ansluten) ska den utföras enligt ELSÄK-FS 2008:1 om utförande av elektriska anläggningar. För elektriska anläggningar finns inga krav på CE-märkning.
HU: Kell-e CE-jelöléssel ellátni egy elosztószekrényt?
Magyar: Ha az elosztószekrény funkcionális egységként vásárolható meg, akkor terméknek minősül, amelyet az 1993:1068-as rendelet és az Elsäkerhetsverket ELSÄK-FS 2000:1 előírása szerint kell legyártani. A gyártónak műszaki dokumentációt és EK-megfelelőségi nyilatkozatot kell készítenie, és CE-jelöléssel kell ellátnia a szekrényt. Ha az elosztószekrényt helyszínen szerelik össze és a kész berendezés részét képezi (rögzítetten csatlakoztatva), akkor az ELSÄK-FS 2008:1 előírása szerint kell kivitelezni. Helyszínen épített villamos berendezésekre nem vonatkoznak CE-jelölési követelmények.

16. kérdés / Fråga 16
SV: Måste man följa svensk standard vid utförande av elanläggningar?
Svenska: Vill man vara säker på att man gör rätt, och inte själv behöva svara för att en egen säkerhetslösning ger betryggande säkerhet, ska man tillämpa svensk standard. Föreskrifterna anger de grundläggande säkerhetskraven men ger möjlighet till alternativa utföranden. Om ett utförande avviker från svensk standard ska de bedömningar som ligger till grund för utförandet dokumenteras. Den som väljer ett alternativt utförande har ansvaret för att konstruktionen är dokumenterad och ger betryggande säkerhet. (1§, 2 kap. ELSÄK-FS 2008:1)
HU: Kötelező-e a svéd szabványt követni villamos berendezések kivitelezésekor?
Magyar: Ha biztos akar lenni abban, hogy helyesen jár el, és nem kell egyedül igazolnia, hogy a saját biztonsági megoldása megfelelő védelmet nyújt, alkalmazza a svéd szabványt. Az előírások csak az alapvető biztonsági követelményeket határozzák meg, és lehetővé tesznek alternatív megoldásokat is. Ha a kivitelezés eltér a svéd szabványtól, dokumentálni kell az eltérés alapjául szolgáló értékeléseket. Az alternatív megoldást választó felelős azért, hogy a kivitelezés dokumentált legyen és megfelelő biztonságot nyújtson. (1§, 2 kap. ELSÄK-FS 2008:1)

17. kérdés / Fråga 17
SV: Vad avses med svensk standard?
Svenska: Svensk standard inom elområdet utarbetas och fastställs av SEK Svensk Elstandard. SEK är ingen myndighet utan en ideell organisation med frivilligt deltagande från myndigheter, företag och organisationer. De allra flesta svenska standarder har sin grund i europeisk eller internationell standard – så är det även med SS 4364000+R1, elinstallationsreglerna. Svensk standard har inte status som föreskrift och ingår inte i ellagstiftningen utan är ett hjälpmedel för att uppfylla kraven i lagstiftningen. När SEK meddelar att en standard upphör att gälla, upphör också dess status som svensk standard – man kan alltså inte åberopa att en anläggning är utförd enligt svensk standard om standarden har upphört att gälla då anläggningen togs i drift.
HU: Mit jelent a svéd szabvány?
Magyar: A villamos területen a svéd szabványokat a SEK Svensk Elstandard dolgozza ki és hagyja jóvá. A SEK nem hatóság, hanem önkéntes alapon működő nonprofit szervezet, amelynek tagjai hatóságok, vállalkozások és szervezetek. A legtöbb svéd szabvány európai vagy nemzetközi szabványon alapul – így van ez az SS 4364000+R1, azaz az elinstallationsreglerna esetében is. A svéd szabvány nem rendeleti státuszú és nem része az elektromos jogszabályoknak – csupán segédeszköz a jogszabályi követelmények teljesítéséhez. Ha a SEK bejelenti, hogy egy szabvány hatályát veszti, az többé nem tekinthető svéd szabványnak – tehát nem lehet arra hivatkozni, hogy a berendezés svéd szabvány szerint készült, ha az üzembe helyezéskor a szabvány már hatályon kívül volt.

18. kérdés / Fråga 18
SV: Vad gäller när det kommer nya utgåvor av standarder?
Svenska: Elinstallationsreglerna kommer att behöva uppdateras närmast fortlöpande. Om anläggningens säkerhet avviker från den nya utgåvan ska de bedömningar som ligger till grund för utförandet vara dokumenterade – dokumentationen kan då visa på att installationen överensstämmer med en tidigare utgåva av standarden. Exempel: Utgåva 1 upphör att gälla sista mars 2010. Om installationen färdigställs efter mars 2010 måste dokumentationen visa att anläggningen är utförd enligt utgåva 1.
HU: Mi a teendő, ha egy szabvány új kiadása jelenik meg?
Magyar: Az elinstallationsreglernát folyamatosan frissíteni kell majd. Ha a berendezés biztonsága eltér az új kiadástól, dokumentálni kell a kivitelezés alapjául szolgáló értékeléseket – a dokumentáció ekkor igazolhatja, hogy a telepítés egy korábbi kiadásnak felel meg. Példa: Az 1. kiadás 2010. március végén veszti hatályát. Ha a telepítés 2010 márciusa után készül el, a dokumentációban fel kell tüntetni, hogy a berendezés az 1. kiadás szerint készült.

19. kérdés / Fråga 19
SV: Är det förbjudet att utföra en elinstallation enligt en tidigare utgåva av en standard?
Svenska: Generellt kan man nog svara nej. Men den utförda anläggningen anses inte vara utförd enligt svensk standard. Bara för att det kommer en ny utgåva behöver det inte innebära att den äldre utgåvan inte uppfyller de grundläggande säkerhetskraven. En anläggning kan vara utförd enligt en tidigare utgåva och likväl anses uppfylla kravet på betryggande säkerhet. Om Elsäkerhetsverket vill förbjuda ett visst utförande torde detta endast kunna göras genom föreskrift. (1§, 2 kap. ELSÄK-FS 2008:1)
HU: Tilos-e egy berendezést egy szabvány korábbi kiadása szerint kivitelezni?
Magyar: Általában nem. A kivitelezett berendezés azonban nem tekinthető svéd szabvány szerint kivitelezettnek. Önmagában az, hogy egy szabvány új kiadása jelenik meg, nem jelenti automatikusan, hogy a régebbi kiadás nem teljesíti az alapvető biztonsági követelményeket. Egy berendezés kivitelezhető korábbi kiadás szerint, és mégis megfelelő biztonságot nyújthat. Ha az Elsäkerhetsverket meg akar tiltani egy bizonyos kivitelezési módot, ezt csak rendelet útján teheti meg. (1§, 2 kap. ELSÄK-FS 2008:1)

20. kérdés / Fråga 20
SV: Kan man söka dispens om ett utförande avviker från svensk standard?
Svenska: Nej. Varken Elsäkerhetsverket eller SEK Svensk Elstandard kan eller får bevilja dispenser för avvikande från svensk standard. Avvikelser som inte avser elsäkerhet behöver inte dokumenteras, t.ex. antalet uttag i ett rum eller höjdavvikelser för placering av strömställare. Om en anläggning från elsäkerhetssynpunkt avviker från svensk standard ska dock de bedömningar som legat till grund för utförandet vara dokumenterade och kunna uppvisas för Elsäkerhetsverket.
HU: Lehet-e felmentést kérni, ha a kivitelezés eltér a svéd szabványtól?
Magyar: Nem. Sem az Elsäkerhetsverket, sem a SEK Svensk Elstandard nem adhat felmentést a svéd szabványtól való eltérésre. Az elektromos biztonságot nem érintő eltéréseket – például a szobánkénti konnektorok száma vagy a kapcsolók elhelyezési magassága – nem szükséges dokumentálni. Ha azonban a berendezés elektromos biztonsági szempontból eltér a svéd szabványtól, a kivitelezés alapjául szolgáló értékeléseket dokumentálni kell, és az Elsäkerhetsverket kérésére be kell mutatni.

21. kérdés / Fråga 21
SV: Om vi väljer att inte följa elinstallationsreglerna vad gäller kontrollerna i del 6, vad gäller då; måste vi dokumentera kontrollerna?
Svenska: Delarna 1–5 och 7 i elinstallationsreglerna ger regler för utförande av elinstallationer. Del 6 handlar om kontroll och detta regleras av andra myndighetsbestämmelser – starkströmsförordningen och ELSÄK-FS 2008:2 – vilka är bindande och kan vara mer omfattande än standardens fordringar. Elinstallatören är ytterst ansvarig för kontrollen och bestämmer hur den ska utföras. En tillämpning av del 6 får inte antas uppfylla ellagstiftningens bestämmelser, varför avvikelser från del 6 inte behöver dokumenteras. (7§, Elinstallatörsförordning SFS 1990:806)
HU: Ha nem követjük az elinstallationsreglerna 6. részét az ellenőrzések tekintetében, kell-e dokumentálni az eltéréseket?
Magyar: Az elinstallationsreglerna 1–5. és 7. része a kivitelezési szabályokat tartalmazza. A 6. rész az ellenőrzésről szól, amelyet más hatósági rendelkezések – a starkströmsförordning és az ELSÄK-FS 2008:2 – szabályoznak, és ezek kötelező jellegűek, sőt szigorúbbak is lehetnek a szabványénál. A villanyszerelő végső soron felelős az ellenőrzésért, és ő dönti el, hogyan hajtja végre. Mivel a 6. rész alkalmazása önmagában nem jelenti az elektromos jogszabályok teljesítését, az attól való eltéréseket nem szükséges dokumentálni. (7§, Elinstallatörsförordning SFS 1990:806)

22. kérdés / Fråga 22
SV: På firman har vi olika uppfattningar; måste man använda jordfelsbrytare på vägguttag när man bygger ut en befintlig villa?
Svenska: Vid utförande av starkströmsanläggningar inom bostäder, grundskolor, förskolor, fritids- och daghem ska det installeras tilläggsskydd i form av jordfelsbrytare med högsta märkutlösningsström 30 mA för alla uttag med märkström upp till och med 16 A. Undantag medges endast om avbrott i uttaget skulle medföra allvarliga konsekvenser. Vid utvidgning inom ett befintligt torrt rum i bostäder, grundskolor m.fl. får uttag installeras utan jordfelsbrytare under förutsättning att den befintliga anläggningen är utförd enligt ELSÄK-FS 1994:7 eller äldre bestämmelser (före 1 juli 2000). Detta undantag gäller endast inom befintligt torrt rum – inte inom nya rum eller fuktiga/våta utrymmen. (ELSÄK-FS 2008:1)
HU: Cégünknél eltérő vélemények vannak: kötelező-e áramvédő kapcsolót (jordfelsbrytare) felszerelni a fali konnektorokhoz meglévő villa bővítésekor?
Magyar: Lakásokban, általános iskolákban, óvodákban és napközikben az erős áramú berendezések kivitelezésekor kiegészítő védelemként legfeljebb 30 mA névleges kioldási áramú áramvédő kapcsolót kell felszerelni minden legfeljebb 16 A-es konnektorhoz. Kivétel csak akkor tehető, ha a konnektor kikapcsolása súlyos következményekkel járna. Meglévő száraz helyiség bővítésekor – lakásban, általános iskolában stb. – a konnektor felszerelhető áramvédő kapcsoló nélkül, ha a meglévő berendezés az ELSÄK-FS 1994:7 vagy korábbi előírások szerint készült (2000. július 1. előtt). Ez a kivétel kizárólag meglévő száraz helyiségre vonatkozik – új helyiségekre, nedves vagy vizes helyiségekre nem. (ELSÄK-FS 2008:1)

23. kérdés / Fråga 23
SV: I utgåva 1 av elinstallationsreglerna fanns det undantag för skydd mot indirekt beröring vid utvidgning av befintlig anläggning inom bl.a. bostadsrum – man behövde inte ansluta utsatta delar till skyddsjord och kunde komplettera med ojordade uttag. Har detta undantag slopats?
Svenska: Nej. Elsäkerhetsverket ger två undantag vid utvidgning av lågspänningsanläggningar. Dels behöver utsatta delar inte anslutas till skyddsjord om de befintliga utsatta delarna inte är anslutna till skyddsjord och anläggningen är utförd före 1 januari 1994. Dels får man installera uttag i ett befintligt torrt rum inom bostäder, grundskolor m.fl. utan att uttagen måste föregås av jordfelsbrytare, under förutsättning att anläggningen är utförd enligt ELSÄK-FS 1994:7 eller äldre bestämmelser. I ett utrymme där man har ojordade uttag får man inte införa jordade uttag – möjligheten för samtidig beröring av jordade och ojordade utsatta delar medför en ökad risk för olycka. Se även fråga 35.
HU: Az elinstallationsreglerna 1. kiadásában volt kivétel a meglévő berendezések – például lakóhelyiségek – bővítésekor az indirekt érintés elleni védelemre; nem kellett a nem védőföldelt konnektorokat pótlólag felváltani. Ezt a kivételt eltörölték?
Magyar: Nem. Az Elsäkerhetsverket két kivételt tesz lehetővé kisfeszültségű berendezések bővítésekor. Egyrészt a kitett fémalkatrészeket nem kell védőföldre csatlakoztatni, ha a meglévő kitett részek sem csatlakoznak védőföldre, és a berendezés 1994. január 1. előtt készült. Másrészt meglévő száraz helyiségben – lakásban, általános iskolában stb. – felszerelhető konnektor áramvédő kapcsoló nélkül, ha a berendezés az ELSÄK-FS 1994:7 vagy korábbi előírások szerint készült. Fontos: olyan helyiségben, ahol nem védőföldelt konnektorok vannak, nem szabad védőföldelt konnektorokat bevezetni – a kettő egyidejű érintésének lehetősége fokozott balesetveszélyt jelent. Lásd még a 35. kérdést.

24. kérdés / Fråga 24
SV: Varför anges inte hela kapslingsklassen i elinstallationsreglerna? Man kan som exempel se IP2X, IPX5 och IPXXB.
Svenska: I elinstallationsreglerna anges minimikraven på skydd mot faror. De olika kapitlen behandlar olika typer av faror och anger kraven på skydd mot beskriven fara – därför anges endast den grad av skydd som är relevant i det aktuella kapitlet. Kapitel 41 anger kraven på skydd mot elchock: behovet av skydd mot vatten regleras inte i detta kapitel, varför denna position lämnas med ett X, till exempel IP2X. I badrum anges kapslingsklassen för skydd mot inträngande av vatten (701.512.2) men skydd mot inträngande av främmande föremål är inte reglerat i denna del, varför denna position anges med X, t.ex. IPX1. IPXXB innebär att varken skydd mot främmande föremål eller mot vatten anges i det aktuella kapitlet – bara skydd mot beröring med ett finger (B).
HU: Miért nem adják meg a teljes tokozási fokozatot az elinstallationsreglernában? Például IP2X, IPX5 és IPXXB jelöléseket láthatunk.
Magyar: Az elinstallationsreglernában az egyes veszélyekkel szembeni minimális védelmi követelményeket adják meg. Az egyes fejezetek különböző típusú veszélyekkel foglalkoznak, és csak a saját fejezetükben releváns védelmi szintet határozzák meg – a többi pozíciót X-szel jelölik. A 41. fejezet az elektromos ütés elleni védelmet tárgyalja: a vízbehatás elleni védelem itt nem szabályozott, ezért az a pozíció X marad, például IP2X. Fürdőszobákban a vízbehatás elleni tokozási fokozatot adják meg (701.512.2), de az idegentestbehatolás elleni védelem ebben a részben nem szabályozott, ezért ott is X szerepel, például IPX1. Az IPXXB jelölés esetén sem az idegentestbehatolás, sem a vízbehatás elleni védelem nincs meghatározva az adott fejezetben – csupán az ujjal való érintés elleni védelem (B betű).

25. kérdés / Fråga 25
SV: Kan elinstallationsreglerna tillämpas vid utförande av en maskin?
Svenska: Elinstallationsreglerna gäller för projektering, montering och kontroll av elinstallationer för lågspänning. Av punkt 11.3 framgår att standarden inte gäller för maskiners elutrustning. Som svensk standard för maskiners elutrustning gäller SS-EN 60204-1, Maskinsäkerhet – Maskiners elutrustning – Del 1: Allmänna fordringar.
HU: Alkalmazhatók-e az elinstallationsreglerna egy gép kivitelezésénél?
Magyar: Az elinstallationsreglerna kisfeszültségű villamos telepítések tervezésére, szerelésére és ellenőrzésére vonatkozik. A 11.3. pontból kiderül, hogy a szabvány nem vonatkozik a gépek elektromos berendezéseire. Erre a célra az SS-EN 60204-1 szabvány irányadó: Gépek biztonsága – Gépek elektromos berendezései – 1. rész: Általános követelmények.

26. kérdés / Fråga 26
SV: Måste biledaren i EKRK vara ansluten i båda ändarna?
Svenska: Nej. Varken produktstandarden för EKRK eller elinstallationsreglerna ställer krav på att aluminiumskärmens biledare ska vara ansluten till jord. Aluminiumhöljet på en EKRK är inte en utsatt del – definitionen av utsatt del är en för beröring åtkomlig ledande del av elmateriel, som normalt inte är spänningssatt, men som på grund av fel i den grundläggande isoleringen kan anta en farlig spänning. Skärmen är inte åtkomlig för beröring och är därmed inte en utsatt del. Aluminiumhöljet måste inte vara anslutet till jord men får vara det. Om man väljer att jordförbinda skärmen finns det i vart fall inga krav på att den ska vara ansluten i båda ändar. Se även fråga 58.
HU: Az EKRK kábel árnyékolásának (biledaren) mindkét végén csatlakoztatottnak kell lennie?
Magyar: Nem. Sem az EKRK termékszabványa, sem az elinstallationsreglerna nem írja elő, hogy az alumíniumárnyékolást földhöz kell csatlakoztatni. Az alumíniumburkolat nem kitett fémalkatrész – a kitett fémalkatrész definíciója szerint érintkezéssel hozzáférhető, normálisan feszültség alatt nem álló, de szigetelési hiba esetén veszélyes feszültséget felvehető vezető alkatrész. Az árnyékolás érintkezéssel nem hozzáférhető, ezért nem minősül kitett fémalkatrésznek. Az alumíniumburkolat nem kötelező, de lehet földelni. Ha mégis földelik, nem szükséges mindkét végén csatlakoztatni – egy végpont is elegendő. Lásd még a 58. kérdést.

27. kérdés / Fråga 27
SV: Vad avses med skyddsledare?
Svenska: Skyddsledare är ett samlingsnamn för alla ledare som är anordnade av elsäkerhetsskäl, t.ex. för skydd mot elchock. Skyddsledare avsedda för ett visst ändamål kan ha ett specifikt namn såsom skyddsjordsledare, som är en skyddsledare avsedd för skyddsjordning. Även skyddsutjämningsledare, PEN-ledare och jordtagsledare är skyddsledare. Se även fråga 60.
HU: Mit jelent a „védővezető" (skyddsledare) fogalma?
Magyar: A védővezető gyűjtőfogalom minden olyan vezető számára, amelyet biztonsági okokból – például elektromos ütés elleni védelemre – alakítanak ki. Az egyes rendeltetésű védővezetőknek külön nevük is lehet: például a skyddsjordsledare (védőföldelési vezető) a védőföldelésre szánt védővezető. A kiegyenlítővezető (skyddsutjämningsledare), a PEN-vezető és a földelési vezető (jordtagsledare) szintén védővezetők. Lásd még a 60. kérdést.

28. kérdés / Fråga 28
SV: Allpolig brytning är inte definierat. Innebär detta att neutralledaren måste frånskiljas i vanliga elinstallationer?
Svenska: Ordet allpolig används inte i elinstallationsreglerna. Kraven på vilka ledare som ska frånkopplas och frånskiljas framgår av kapitel 53. Enligt de grundläggande fordringarna ska varje strömkrets kunna frånskiljas från samtliga matande spänningsförande ledare. Neutralledaren är per definition att betrakta som spänningsförande ledare men behöver i TN-C-S- och TN-S-system inte frånskiljas eller brytas. I utrymme med förhöjd brandrisk (422.2.14) ska dock varje neutralledare ha en frånskiljningsanordning. (536.1.2)
HU: Az „összes pólusú kikapcsolás" fogalma nincs meghatározva. Ez azt jelenti, hogy a semleges vezető megszakítása is kötelező szokványos villamos telepítéseknél?
Magyar: Az „összes pólusú" kifejezés nem szerepel az elinstallationsreglernában. Az 53. fejezet határozza meg, hogy mely vezetőket kell lekapcsolni és elszakítani. Alapkövetelményként minden áramkört le kell tudni választani az összes tápfeszültség-vezető hatóköréből. A semleges vezető definíció szerint feszültség alatt álló vezető, de TN-C-S és TN-S rendszerekben nem szükséges elszakítani. Fokozott tűzveszélyes helyiségekben (422.2.14) azonban minden semleges vezető számára leválasztó berendezést kell biztosítani. (536.1.2)

29. kérdés / Fråga 29
SV: Var finner jag reglerna för användning av anslutningskablar?
Svenska: Ordet anslutningskabel håller på att försvinna i reglerna då ordet egentligen är missvisande – alla kablar är väl anslutningskablar. Regler om användning av flexibla kablar och sladdar finns i avsnitt 521.9. Se även fråga 65.
HU: Hol találhatók a csatlakozókábelekre vonatkozó szabályok?
Magyar: A „csatlakozókábel" szó eltűnőben van a szabályokból, mivel valójában félrevezető – elvégre minden kábel csatlakozókábel. A rugalmas kábelekre és zsinórokra vonatkozó szabályok az 521.9. szakaszban találhatók. Lásd még a 65. kérdést.

30. kérdés / Fråga 30
SV: Finns det någon rekommendation om vilken typ av systemjordning som ska användas i en byggnad?
Svenska: I en byggnad får TN-, TT- och IT-system användas. Om TN-system används ska, vid nybyggnation, TN-S-system användas efter anslutningspunkten. Bokstaven S i TN-S innebär att skyddsfunktionen är utförd med en separat ledare som inte är för normala driftströmmar. I en byggnad som är ansluten till allmänt distributionsnät och har egen kraftförsörjning, t.ex. generatoraggregat eller UPS, ska servisledningen utföras som TN-C-system och den egna kraftförsörjningens neutralpunkt anslutas med en isolerad ledare som inom den egna anläggningen endast är jordförbunden i en punkt, normalt via huvudjordningsskenan. (312.2, 444.4.3.2 och 444.4.6.1)
HU: Van-e ajánlás arra vonatkozóan, hogy egy épületben milyen típusú rendszerföldlést alkalmazzanak?
Magyar: Egy épületben TN-, TT- és IT-rendszerek egyaránt alkalmazhatók. Ha TN-rendszert alkalmaznak, újépítésben a csatlakozási ponton túl TN-S rendszert kell használni. A TN-S-ben az S betű azt jelenti, hogy a védőfunkciót egy különálló vezető látja el, amelyen normál üzemi áramok nem folynak. Ha az épület mind a közüzemi elosztóhálózathoz, mind saját áramforráshoz (pl. aggregáthoz vagy UPS-hez) csatlakozik, a csatlakozó hálózatot TN-C rendszerként kell kiépíteni, a saját áramforrás semlegespontját pedig csak egy pontban – általában a fő földelési sínon keresztül – kell a saját berendezésen belül földhöz csatlakoztatni. (312.2, 444.4.3.2 és 444.4.6.1)

31. kérdés / Fråga 31
SV: Har man rätt att ta hänsyn till sammanlagring och utnyttjandegrad när man ska välja area för en huvudledning?
Svenska: Ja. För att få ett ekonomiskt och tillförlitligt utförande är det viktigt att den maximala belastningen bestäms. I praktiken är summan av alla belastningars maximala strömmar betydligt större än den faktiska belastningsströmmen. Reglerna för överlastskydd (avsnitt 433) ger två villkor som ska vara uppfyllda: IB ≤ In ≤ Iz (1) och I2 ≤ 1,45 × Iz (2). Sammanlagringsfaktorn blir beroende på typ av belastningar och användarkategori. Underlag för belastningsberäkningar och sammanlagring finns i standard SS 4370145 avsnitt 4.2. (311, 433.1, SS 4370145 avsnitt 4.2)
HU: Figyelembe lehet-e venni az egyidejűségi tényezőt és a kihasználási fokot egy fővezeték keresztmetszetének meghatározásakor?
Magyar: Igen. A gazdaságos és megbízható kivitelezés érdekében fontos a maximális terhelés meghatározása. A gyakorlatban a csatlakoztatott fogyasztók névleges áramainak összege lényegesen nagyobb, mint a tényleges terhelési áram. A túlterhelési áramokkal szembeni védelem szabályai (433. szakasz) két feltételt írnak elő: IB ≤ In ≤ Iz (1) és I2 ≤ 1,45 × Iz (2). Az egyidejűségi tényező a terhelések típusától és a felhasználói kategóriától függ. Belastningsberäkningsalapok az SS 4370145 szabvány 4.2. szakaszában találhatók. (311, 433.1, SS 4370145 avsnitt 4.2)

32. kérdés / Fråga 32
SV: Vilka krav gäller för jordtag om systemjordningen är utförd som TT-system?
Svenska: I TT-system är strömkällan, normalt neutralpunkten, direkt förbunden med ett jordtag via en jordelektrod (systemjordtag). Installationens utsatta delar är anslutna till ett annat jordtag (skyddsjordtag). Felströmmens storlek beror till stor del på jordelektrodernas övergångsmotstånd. För att säkerställa automatisk funktion måste normalt jordfelsbrytare användas som felskydd. Vid användning av jordfelsbrytare ska följande två villkor vara uppfyllda: 1) RA ≤ 50/IΔn, där RA är summan av installationens jordelektrodresistans och skyddsledarens resistans för de utsatta delarna, och IΔn är märkutlösningsströmmen för jordfelsbrytaren. 2) De maximala frånkopplingstiderna i tabell 41.1 ska tillämpas för gruppledningar upp till och med 32 A; för huvudledningar gäller 1 sekund. Vid användning av TT-system måste system- och skyddsjordtagens övergångsresistans kontrollmätas.
HU: Milyen követelmények vonatkoznak a TT-rendszer szerinti rendszerföldlésre?
Magyar: TT-rendszerben az áramforrás semlegespontja közvetlenül földhöz csatlakozik egy jordelektródon keresztül (rendszerföldtag). A telepítés kitett fémalkatrészei egy másik jordelektródához csatlakoznak (védőföldelési elektróda). A hibavezető áram nagysága nagymértékben függ a jordelektródák átmeneti ellenállásától. Az automatikus leválasztás biztosítása érdekében általában áramvédő kapcsolót kell alkalmazni. Az áramvédő kapcsoló alkalmazásakor két feltételnek kell teljesülni: 1) RA ≤ 50/IΔn, ahol RA a telepítés jordelektróda-ellenállásának és a védővezetők ellenállásának összege, IΔn az áramvédő kapcsoló névleges kioldási árama. 2) A 41.1. táblázatban megadott maximális kikapcsolási idők érvényesek a legfeljebb 32 A-es csoportvezetékekre; fővezetékekre 1 másodperc vonatkozik. TT-rendszer alkalmazásakor a rendszer- és védőföldelő elektróda átmeneti ellenállását mérésekkel kell ellenőrizni.

33. kérdés / Fråga 33
SV: Är det krav på att anläggningens skyddsanordningar måste vara selektiva? Vi har haft problem med att huvudsäkringar löser ut vid fel i gruppledningar.
Svenska: Elinstallationsreglernas fordringar visar inte på att anläggningens skyddsanordningar måste vara selektiva. Det är användaren och beställaren som visar på behovet av kontinuitet på strömförsörjningen. Därför ska man redan vid projekteringen göra en värdering av varje strömkrets vilka behov det finns på strömförsörjningens kontinuitet – detta styr sedan valet av skyddsanordningar med hänsyn till selektivitet. Man bör även ta hänsyn till sektionering av installationen för att undvika fara och minimera olägenheter vid fel. (avsnitt 314 och kapitel 36)
HU: Kötelező-e, hogy a berendezés védőkészülékei szelektívek legyenek? Problémáink vannak azzal, hogy a főbiztosítók kioldanak a csoportvezetékek hibájánál.
Magyar: Az elinstallationsreglerna nem írja elő, hogy a berendezés védőkészülékeinek szelektíveknek kell lenniük. Az áramellátás folyamatosságára vonatkozó igényt a felhasználó és a megrendelő határozza meg. Ezért már a tervezési szakaszban minden egyes áramkörnél értékelni kell az áramellátás folyamatosságára vonatkozó követelményeket – ez határozza meg a szelektivitás szempontjából megválasztott védőkészülékeket. A berendezés szekcionálásával is érdemes foglalkozni a hibák esetén fellépő veszélyek és kellemetlenségek minimalizálása érdekében. (314. szakasz és 36. fejezet)

34. kérdés / Fråga 34
SV: Får grundisolerade ledningar för olika strömarter och spänningsnivåer förläggas i samma kanalisation?
Svenska: Mitt grundsvar är nej men om vissa villkor är uppfyllda kan ett sådant utförande godkännas. 1) Hänsyn måste tas till de olika ledningarnas isolationsförmåga – grundisolerade ledare för olika spänningar ska var för sig vara isolerade för den högsta förekommande spänningen eller vara åtskilda på annat sätt. 2) Hänsyn måste tas till kunskaper och erfarenheter hos de personer som förväntas utföra underhållet. 3) Hänsyn måste tas till risken för elektromagnetiska störningar. Regler som kan behöva beaktas: 414.4, 444.6, 514.2, 515.2, 521.6, 528.1 och 529.1.
HU: Elhelyezhetők-e ugyanabba a kábelcsatornába különböző áramnemű és feszültségszintű alapszigeteléses vezetékek?
Magyar: Alapvetően nem, de bizonyos feltételek teljesülése esetén elfogadható. 1) Figyelembe kell venni a különböző vezetékek szigetelési képességét – a különböző feszültségszintű alapszigeteléses vezetékeket egyenként a legmagasabb feszültségre kell szigetelni, vagy más módon el kell választani. 2) Figyelembe kell venni a karbantartó személyzet tudását és tapasztalatát. 3) Figyelembe kell venni az elektromágneses zavarok kockázatát. Vonatkozó pontok: 414.4, 444.6, 514.2, 515.2, 521.6, 528.1 és 529.1.

35. kérdés / Fråga 35
SV: Man får inte blanda jordade och ojordade uttag brukar man säga. Men var står detta?
Svenska: Det finns 6 olika typer av skyddsåtgärder i elinstallationsreglerna: automatisk frånkoppling (411), dubbel eller förstärkt isolering (412), skyddsseparation (413, 41C.3), SELV eller PELV (414), isolerad miljö (41C.1), jordfri lokal skyddsutjämning (41C.2). Skyddsåtgärden automatisk frånkoppling förutsätter att utsatta delar är anslutna till skyddsjord – uttag som matar klass I-materiel måste ha skyddsledarkontakt (jordat uttag). Uttag utan skyddsledarkontakt (ojordade uttag) kan användas vid skyddsåtgärden isolerad miljö. Skyddsåtgärden isolerad miljö ska inte sammanblandas med den äldre svenska metoden som användes i bostadsrum fram till och med 1993. Se även fråga 23.
HU: Nem szabad keverni a földelt és nem földelt konnektorokat – de hol van ez leírva?
Magyar: Az elinstallationsreglernában 6 különböző védelmi intézkedés szerepel: automatikus leválasztás (411), kettős vagy megerősített szigetelés (412), védő elválasztás (413, 41C.3), SELV vagy PELV (414), szigetelt környezet (41C.1), földpotenciál mentes helyi kiegyenlítés (41C.2). Az automatikus leválasztáson alapuló védelmi intézkedés megköveteli, hogy a kitett fémalkatrészek védőföldre legyenek csatlakoztatva – az I. osztályú anyagokat tápláló konnektoroknak védővezető-csatlakozóval (földelt konnektorral) kell rendelkezniük. Nem földelt konnektorok a szigetelt környezetű védelmi intézkedésnél alkalmazhatók. Ez a módszer nem tévesztendő össze a régi svéd módszerrel, amelyet lakásokban 1993-ig alkalmaztak. Lásd még a 23. kérdést.

36. kérdés / Fråga 36
SV: Måste det i varje byggnad finnas ett skyddsutjämningssystem?
Svenska: Nej. Skyddsutjämning ingår i skyddsåtgärden automatisk frånkoppling. Om denna metod inte används behöver ingen skyddsutjämning utföras – t.ex. i mindre byggnader utan uttag där skyddsåtgärden dubbel eller förstärkt isolering används för hela installationen. Likaså kan skyddsutjämning utelämnas i byggnader som saknar åtkomliga ledande delar. Begreppet främmande ledande del är definierat – det är en ledande del som normalt har jordpotential. En metallbit på en vägg behöver inte utgöra en främmande ledande del förrän den kan anta en jordpotential. Se även fråga 37.
HU: Minden épületben szükséges-e védő kiegyenlítési rendszer?
Magyar: Nem. A védő kiegyenlítés az automatikus leválasztáson alapuló védelmi intézkedés része. Ha ezt a módszert nem alkalmazzák, nem szükséges védő kiegyenlítés – például kisebb épületeknél, amelyeknek nincs konnektoruk, és az egész telepítésnél kettős vagy megerősített szigetelést alkalmaznak. Szintén elhagyható, ha az épületben nincsenek hozzáférhető vezető részek. Az idegen vezető rész olyan vezető rész, amely normálisan földpotenciálon van – egy falon lévő fémdarab csak akkor minősül annak, ha földpotenciálra kerülhet. Lásd még a 37. kérdést.

37. kérdés / Fråga 37
SV: Kan kort frånkopplingstid ersätta behovet av skyddsutjämning?
Svenska: Skyddsåtgärden skydd mot elchock genom automatisk frånkoppling (411) förutsätter två vidtagna åtgärder. Dels ska utsatta delar vara anslutna till skyddsjord. Dels förutsätts byggnaden ha ett skyddsutjämningssystem som ska förhindra att det uppkommer farliga beröringsspänningar inom byggnaden när det uppkommer ett fel utanför byggnaden. Vid ett isolationsfel mellan fasledare och skyddsledare kan skyddsledaren anta en spänning om 100–150 V i förhållande till fördelningssystemets jordtag. Varken jordfelsbrytare eller kort frånkopplingstid för överströmsskydd kan ersätta kravet på skyddsutjämning.
HU: Helyettesítheti-e a rövid kikapcsolási idő a védő kiegyenlítési rendszer szükségességét?
Magyar: Nem. Az automatikus leválasztáson alapuló védelmi intézkedés (411) két feltételt igényel. Egyrészt a kitett fémalkatrészeket védőföldre kell csatlakoztatni. Másrészt az épületnek rendelkeznie kell védő kiegyenlítési rendszerrel, amely megakadályozza a veszélyes érintési feszültség kialakulását az épületen belül, ha az épületen kívül hiba keletkezik. Fázis- és védővezető közötti szigetelési hiba esetén a védővezető 100–150 V feszültséget vehet fel az elosztórendszer földelési pontjához képest. Sem az áramvédő kapcsolók, sem a rövid kikapcsolási idejű túláramvédők nem helyettesíthetik a védő kiegyenlítési rendszert.

38. kérdés / Fråga 38
SV: Måste diskbänksplåten anslutas till skyddsutjämningen?
Svenska: Nej. Om det blir ett isolationsfel i t.ex. spisen och det uppkommer en farlig beröringsspänning mellan spishöljet och diskbänksplåten, ska skyddsapparaten automatiskt frånkoppla felet. Om felet uppstår utanför byggnaden ska redan de metallrörledningar som förs in i byggnaden vara anslutna till skyddsutjämning, och därmed kommer spishöljet och diskbänksplåten att anta samma potential. Om rörledningarna är av isolermateriel och diskbänksplåten inte har kontakt med jord, är diskbänksplåten ingen främmande ledande del och uppkommer ingen beröringsspänning. Se även fråga 37.
HU: Csatlakoztatni kell-e a mosogató fém munkalapját a védő kiegyenlítőhöz?
Magyar: Nem. Ha például a tűzhelyen szigetelési hiba keletkezik és veszélyes érintési feszültség lép fel a tűzhely és a munkalap között, a védelmi készüléknek automatikusan le kell kapcsolnia a hibát. Ha a hiba az épületen kívül keletkezik, a fémcsővezetékeknek már az épületbe való belépés előtt a védő kiegyenlítőhöz kell csatlakozniuk – így a tűzhely és a munkalap azonos potenciálra kerül. Ha a csővezetékek szigetelő anyagból vannak, és a munkalap nem érintkezik a talajjal, a munkalap nem idegen vezető rész, és nem keletkezik érintési feszültség. Lásd még a 37. kérdést.

39. kérdés / Fråga 39
SV: Vad är det för skillnad på skyddsutjämning och kompletterande skyddsutjämning?
Svenska: Skyddsutjämning är ett grundvillkor vid skyddsåtgärden automatisk frånkoppling och ska förhindra farlig beröringsspänning inom en byggnad vid fel utanför byggnaden. Den utförs i en central punkt i byggnaden, normalt där försörjningssystemen förs in, och omfattar inkommande skyddsledare, främmande ledande delar, metallrörledningar och berörbara armeringsjärn. Den ansluts till byggnadens huvudjordningsskena. Kompletterande skyddsutjämning är ett tilläggsskydd som utförs lokalt för en del av installationen eller ett rum. Behovet styrs av miljön och syftet är att begränsa beröringsspänningen till 50 V oberoende av frånkopplingstiden. Den ska innefatta alla samtidigt berörbara ledande delar och vara ansluten till skyddsledare hos all materiel. Se även fråga 37.
HU: Mi a különbség a védő kiegyenlítés és a kiegészítő védő kiegyenlítés között?
Magyar: A védő kiegyenlítés az automatikus leválasztáson alapuló védelmi intézkedés alapvető feltétele, és célja az épületen belüli veszélyes érintési feszültség megakadályozása, ha az épületen kívül hiba keletkezik. Az épület egy központi pontján – általában ott, ahol az ellátó rendszerek belépnek – valósul meg, és magában foglalja a bejövő védővezetőket, az idegen vezető részeket, a fémcsővezetékeket és a betonvas hálózatokat. A fő földelési sínhez csatlakozik. A kiegészítő védő kiegyenlítés helyi kiegészítő védelem, amelyet a telepítés egy részére vagy egy helyiségre alkalmaznak. Célja az érintési feszültség 50 V alá csökkentése a kikapcsolási időtől függetlenül. Minden egyidejűleg érinthető vezető részt magában kell foglalnia, és minden anyag védővezetőjéhez csatlakoznia kell. Lásd még a 37. kérdést.

40. kérdés / Fråga 40
SV: Hur lång frånkopplingstid kan accepteras för en trefasledning med märkström 25 A och huvudspänning 400 V som matar en verktygsmaskin?
Svenska: För gruppledningar upp till och med 32 A ska frånkopplingstiderna som ges i tabell 41.1 tillämpas. Om fasspänningen är 230 V ska frånkoppling ske inom 0,4 sekunder.
HU: Mekkora kikapcsolási idő fogadható el egy 25 A névleges áramú, 400 V főfeszültségű, szerszámgépet tápláló háromfázisú kábelnél?
Magyar: A legfeljebb 32 A névleges áramú csoportvezetékeknél a 41.1. táblázatban megadott kikapcsolási idők érvényesek. Ha a fázisfeszültség 230 V, a kikapcsolásnak 0,4 másodpercen belül kell megtörténnie.

41. kérdés / Fråga 41
SV: Vilken längsta frånkopplingstid gäller vid jordfel i en huvudledning som ingår i det allmänna distributionsnätet?
Svenska: För alla gruppledningar med märkström över 32 A och för alla huvudledningar, oberoende av märkström, ska frånkoppling ske inom 5 sekunder. Längre frånkopplingstid kan tillåtas i det allmänna distributionsnätet och för utsatta delar i gatu- och vägbelysningar under förutsättning att en riskhantering har genomförts. En rapport från ELFORSK hävdar att de nätdelar som visat sig kunna ge förhöjda risker är luftledningsnät på landsbygd med frånkopplingstider på över 10 sekunder. (411.3.2.3 och 714.411.3.2.3)
HU: Mi a maximális kikapcsolási idő egy fővezetéken bekövetkező földhibánál?
Magyar: Minden 32 A feletti névleges áramú csoportvezetékre és minden fővezetékre – névleges áramtól függetlenül – a kikapcsolásnak 5 másodpercen belül kell megtörténnie. Hosszabb kikapcsolási idő megengedett a közüzemi elosztóhálózatban és utca- és közúti világítás kitett fémalkatrészeinél, ha kockázatkezelést hajtottak végre. Egy ELFORSK-jelentés szerint a fokozott kockázatot mutató hálózatrészek a vidéki légvezetékes hálózatok, ahol a kikapcsolási idő meghaladja a 10 másodpercet. (411.3.2.3 és 714.411.3.2.3)

42. kérdés / Fråga 42
SV: Det finns inga frånkopplingstider för IT-system. Behöver inte dessa nät frånkopplas vid fel?
Svenska: Felströmmen vid ett första fel i ett IT-system blir normalt så låg att det inte uppkommer någon farlig beröringsspänning, varför detta första fel normalt inte behöver frånkopplas. Felet ska dock avhjälpas så snart som möjligt. Om första felet kvarstår och ett andra fel inträffar från annan fasledare uppstår en tvåpolig jordslutning med hög felström som följd. Frånkopplingstiderna som anges för TN-system kan tillämpas.
HU: IT-rendszernél nincsenek kikapcsolási idők meghatározva. Nem kell lekapcsolni ezeket a hálózatokat hiba esetén?
Magyar: IT-rendszerben az első hiba esetén a hibavezető áram általában annyira alacsony, hogy nem okoz számottevő érintési feszültséget, ezért az első hibát általában nem szükséges kikapcsolni. A hibát azonban a lehető leghamarabb el kell hárítani. Ha az első hiba fennmarad és egy másik fázisvezetőn is hiba keletkezik, kétpólusú földzárás jön létre nagy hibavezető árammal, amelyet ki kell kapcsolni. Ilyenkor a TN-rendszernél megadott kikapcsolási idők alkalmazhatók.

43. kérdés / Fråga 43
SV: Varför tillåter man längre frånkopplingstider i TN-system än för TT-system?
Svenska: Vid ett fel till skyddsjordat utsatt del uppstår en spänningsdelning och den utsatta delens potential mot jord blir lägre än fasspänningen. Beröringsspänningen i ett TN-system har antagits vara 40 % av nominell fasspänning, det vill säga 92 V vid U₀ = 230 V. I ett TT-system, som inte har metallisk förbindelse mellan utsatt del och strömkällan, kan beröringsspänningen bli nära lika med fasspänningen. En högre beröringsspänning ger en större ström genom kroppen och leder till behov av kortare frånkopplingstider.
HU: Miért engednek meg hosszabb kikapcsolási időt TN-rendszernél, mint TT-rendszernél?
Magyar: TN-rendszerben, ha hiba keletkezik a védőföldelt kitett fémalkatrész és a fázisvezető között, feszültségosztás jön létre, és a kitett fémalkatrész földhöz viszonyított feszültsége a fázisfeszültségnél alacsonyabb. TN-rendszerben az érintési feszültséget a névleges fázisfeszültség 40%-ára becsülik – azaz kb. 92 V 230 V-os U₀ esetén. TT-rendszerben – ahol nincs fémkapcsolat a kitett fémalkatrész és az áramforrás között – az érintési feszültség megközelítheti a fázisfeszültséget. A magasabb érintési feszültség nagyobb testáramot okoz, ami rövidebb kikapcsolási időt tesz szükségessé.

44. kérdés / Fråga 44
SV: Det står i avsnitt 544 att en skyddsutjämningsledare av koppar ska ha en area om minst 6 mm² men behöver inte vara större än 25 mm². Vad är det som styr om det ska vara 6 mm² eller 25 mm²?
Svenska: Skyddsutjämningsledare är en skyddsledare och ska uppfylla fordringarna i både avsnitt 543 och 544. Om största fasledare inom installationen har en area om 16 mm² koppar kan skyddsutjämningsledarens area väljas från tabell 54.3 – vilket då blir 16 mm². Om fasledaren istället har arean 95 mm² behöver skyddsutjämningsledarens area inte vara större än 25 mm² enligt avsnitt 544. (543 och 544)
HU: A 544. szakaszban az áll, hogy a rézből készült védő kiegyenlítővezető keresztmetszete legalább 6 mm², de nem kell nagyobbnak lennie 25 mm²-nél. Mi határozza meg a pontos értéket?
Magyar: A védő kiegyenlítővezető védővezető, ezért mind a 543., mind a 544. szakasz követelményeinek meg kell felelnie. Ha a telepítés legnagyobb fázisvezető keresztmetszete 16 mm² réz, a védő kiegyenlítővezető keresztmetszete az 54.3. táblázatból választható – ez esetben 16 mm². Ha a fázisvezető keresztmetszete 95 mm², a védő kiegyenlítővezető keresztmetszete a 544. szakasz szerint nem kell, hogy 25 mm²-nél nagyobb legyen. (543 és 544)

45. kérdés / Fråga 45
SV: Vad menas med "under överinseende av fackkunniga eller instruerade personer" som det står i anmärkningen till 411.3.3?
Svenska: Punkten gäller användande av jordfelsbrytare som tilläggsskydd. Undantag kan göras för uttag som används under överinseende av fackkunniga eller instruerade personer, t.ex. i vissa yrkesmässiga eller industriella lokaler. Riskerna med el anses särskilt stora vid handhållen materiel och sladdar. Jordfelsbrytare kan naturligtvis användas i betydligt fler fall än vad minimifordringarna kräver. Fordringarna i 411.3.3 ställer dessutom krav på att jordfelsbrytare med märkutlösningsström högst 30 mA ska vara utfört för alla uttag med märkström upp till 20 A för allmänbruk av lekmän – och i bostäder gäller detta samtliga uttag upp till 20 A.
HU: Mit jelent a 411.3.3-ban említett „szakemberek vagy instruált személyek felügyelete"?
Magyar: Ez a pont az áramvédő kapcsolók kiegészítő védelemként való alkalmazásáról rendelkezik. Kivétel tehető olyan konnektoroknál, amelyeket szakemberek vagy instruált személyek felügyelete alatt használnak, pl. bizonyos szakmai vagy ipari helyiségekben. Az elektromos veszélyek különösen nagynak tekinthetők kézi anyagok és zsinórok esetén. Az áramvédő kapcsolók természetesen a minimumkövetelményeknél jóval több esetben is alkalmazhatók. A 411.3.3 előírásai szerint lakásokban minden legfeljebb 20 A-es konnektort áramvédő kapcsolóval kell ellátni.

46. kérdés / Fråga 46
SV: Hur vet jag att säkringen frånkopplar felet inom de tider som anges i kapitel 41?
Svenska: SEK har givit ut en handbok (SEK HB 421) som innehåller två standarder om hur man kan kontrollera att kravet på automatisk frånkoppling är uppfyllt. I SS 4241406, Ledningsnät för max 1000 V, finns anvisningar om längsta kabellängd som får användas när säkringar används som skyddsapparat. SS 4241404 gäller för dvärgbrytare. Dessa standarder är tillämpbara för direktjordade nät om den nominella fasspänningen är 230 V. Om kabellängden inte överstiger de längder som anges i tabellerna kan kravet på frånkoppling anses vara uppfyllt.
HU: Honnan tudom, hogy a biztosító a 41. fejezetben megadott időn belül kapcsol ki?
Magyar: A SEK kiadott egy kézikönyvet (SEK HB 421), amely két szabványt tartalmaz az automatikus kikapcsolás teljesítésének ellenőrzésére. Az SS 4241406 szabvány (Legfeljebb 1000 V-os hálózatok) útmutatást ad a maximális kábelhosszakról biztosítók esetén. Az SS 4241404 automatikus megszakítókra vonatkozik. Ezek a szabványok 230 V-os névleges fázisfeszültségű közvetlenül földelt hálózatoknál alkalmazhatók. Ha a kábelhossz nem haladja meg a táblázatokban megadott értékeket, az automatikus kikapcsolás követelménye teljesítettnek tekinthető.

47. kérdés / Fråga 47
SV: Kan man få längre ledningslängder om man använder jordfelsbrytare?
Svenska: Ja, i vissa fall. En jordfelsbrytare löser endast för jordfel, men en ledare ska normalt även vara skyddad vid kortslutning i enlighet med reglerna i avsnitt 434. Exempel: En gruppledning i en anläggning med 230 V har som överströmsskydd en säkring med märkström 16 A, kabeltyp EKK med arean 2,5 mm². Om säkringen ska lösa inom 0,4 sekunder får längsta ledningslängd vara 112 m (SS 4241406, tabell 8). Om gruppledningen förses med en jordfelsbrytare som felskydd kan säkringen dimensioneras för 5 sekunders frånkopplingstid – längsta kabellängd blir då 172 m (SS 4241406, tabell 6).
HU: Hosszabb kábelhosszak alkalmazhatók áramvédő kapcsolóval?
Magyar: Igen, bizonyos esetekben. Az áramvédő kapcsoló csak földhibánál old ki, de a kábelt rövidzárlatnál is védeni kell a 434. szakasz szabályai szerint. Példa: Egy 230 V-os, 16 A-es biztosítóval és 2,5 mm²-es EKK-kábellel ellátott csoportvezetéknél, ha a biztosítónak 0,4 másodpercen belül kell kioldania, a maximális kábelhossz 112 m (SS 4241406, 8. táblázat). Ha áramvédő kapcsolót alkalmaznak hibavédelemként, a biztosító 5 másodperces kikapcsolási időre méretezhető – a maximális kábelhossz ekkor 172 m lesz (SS 4241406, 6. táblázat).

48. kérdés / Fråga 48
SV: I kapitel 42 står det att i ett utrymme med förhöjd brandrisk får endast armaturer med begränsad yttemperatur användas. Hur vet man om en armatur har begränsad yttemperatur?
Svenska: I avsnitt 559, som bland annat gäller för belysningsinstallationer, finns i bilaga 55ZA förklaringar av symboler som används på ljusarmaturer. En armatur med begränsad yttemperatur ska ha en särskild symbol (D i triangel) på sig – denna ska sökas i armaturens specifikation och på själva armaturen.
HU: A 42. fejezetben az áll, hogy fokozott tűzveszélyes helyiségekben csak korlátozott felületi hőmérsékletű lámpatestek használhatók. Hogyan lehet tudni, hogy egy lámpatest korlátozott felületi hőmérsékletű?
Magyar: Az 55ZA mellékletben (559. szakasz) magyarázatokat adnak a lámpatesteken használt szimbólumokhoz. A korlátozott felületi hőmérsékletű lámpatesten egy különleges szimbólumnak (D háromszögben) kell szerepelnie – ezt a lámpatest specifikációjában és magán a lámpatesten kell keresni.

49. kérdés / Fråga 49
SV: Hur stor säkring får man ha som överlastskydd? Det verkar inte finnas några tabeller som visar på sambandet mellan säkringens märkström och minsta belastningsförmåga?
Svenska: Sambandet mellan en ledarens belastningsförmåga och skyddets märkström anges i elinstallationsreglerna som två villkor: IB ≤ In ≤ Iz (1) och I2 ≤ 1,45 × Iz (2). För smältsäkringar tillverkade enligt SS-EN 60269-1 påverkas faktorn för I2 av märkströmmen: för säkringar med märkström från och med 13 A gäller I2 = 1,6 × In; för 6 A och 10 A gäller I2 = 1,9 × In. Minsta belastningsförmåga för en ledare skyddad av en 10 A säkring: Iz ≥ (10 × 1,9) / 1,45 = 13,1 A.
HU: Mekkora lehet a biztosító maximális névleges árama a túlterhelés elleni védelemhez?
Magyar: A vezető terhelhetősége és a biztosító névleges árama közötti összefüggést az elinstallationsreglerna két feltételként adja meg: IB ≤ In ≤ Iz (1) és I2 ≤ 1,45 × Iz (2). Az SS-EN 60269-1 szerint gyártott olvadóbiztosítókra az I2 értéke: 13 A és nagyobb névleges áramnál = 1,6 × In; 6 A és 10 A-es névleges áramnál = 1,9 × In. Minimálisan szükséges terhelhetőség egy 10 A-es biztosítóhoz: Iz ≥ (10 × 1,9) / 1,45 = 13,1 A.

50. kérdés / Fråga 50
SV: Vad gäller för en- och flerfasbelastningar på samma gruppledning?
Svenska: I de fall man blandar utrustningar avsedda för olika spänningar på samma gruppledning finns risk för brand om endast en fasledare frånkopplas vid fel. Den frånkopplade fasen kan då få såväl högre som lägre spänning än den nominella beroende på eventuell fasförskjutning. Ett sätt att anordna säker frånkoppling är att använda ett flerpoligt överströmsskydd som automatiskt frånkopplar samtliga fasledare vid ett fel. Undantag kan dock göras för industriella lokaler med kontroll på användningen, eller för materiel som tål de påkänningar som kan uppstå. Säker frånkoppling förutsätter att såväl jordfel som fel mellan spänningsförande delar frånkopplas, varför jordfelsbrytare inte kan ersätta flerpoligt överströmsskydd.
HU: Mi érvényes az egy- és háromfázisú terhelések esetén, ha ugyanazon a csoportvezetéken vannak?
Magyar: Ha különböző feszültségű berendezések vannak ugyanazon a csoportvezetéken, tűzveszély áll fenn, ha hiba esetén csak egy fázisvezető kapcsolódik le – a lekapcsolt fázisvezető a faseltolódástól függően a névlegesnél magasabb vagy alacsonyabb feszültséget is felvehet. A biztonságos lekapcsolás egyik módja a többpólusú túláramvédő alkalmazása, amely hiba esetén egyszerre kapcsolja le az összes fázisvezetőt. Kivételek tehetők ipari helyiségekben, ahol az alkalmazást ellenőrzik, vagy olyan anyagoknál, amelyek ellenállnak a feszültség fennmaradásának. Mivel a biztonságos lekapcsolás mind a földhibák, mind a feszültség alatti részek közötti hibák lekapcsolását igényli, az áramvédő kapcsolók nem helyettesíthetik a többpólusú túláramvédőket.

51. kérdés / Fråga 51
SV: Kan man nyttja reglerna om alternativ placering av överlastskydd och kortslutningsskydd även ute i installationerna eller gäller de bara för ledningar i centraler?
Svenska: Förutsättningarna i elinstallationsreglerna om alternativ placering gäller för elinstallationer i allmänhet men inte för kopplingsutrustningar. För en ledning som inte är skyddad vid kortslutning får ledningens överlastskydd placeras upp till 3 m från avgreningspunkten under förutsättning att särskilda åtgärder har vidtagits för att förhindra kortslutning och kabeln inte är placerad nära brännbart material. Förutsättningarna för alternativ placering av överlastskydd finns i avsnitt 433.2.2 och för kortslutningsskydd i avsnitt 434.2.1.
HU: A túlterhelési és rövidzárlat-védelem alternatív elhelyezési szabályai csak az elosztótáblákban lévő kábelekre vonatkoznak, vagy egyéb telepítéseknél is?
Magyar: Az alternatív elhelyezési feltételek általában villamos telepítésekre vonatkoznak, de kapcsolókészülékekre nem. Rövidzárlattal szemben nem védett kábelnél a túlterhelési védőkészülék az elágazási ponttól legfeljebb 3 m-re helyezhető el, feltéve, hogy különleges intézkedéseket tesznek a rövidzárlat ellen és a kábel nincs gyúlékony anyagok közelében. A túlterhelési védelem alternatív elhelyezésének feltételei a 433.2.2. szakaszban, a rövidzárlat-védelméi a 434.2.1. szakaszban találhatók.

52. kérdés / Fråga 52
SV: Vad menas med "utelämnande av överlastskydd" som anges i 433.3? Behöver man ingen säkring i dessa fall?
Svenska: I reglerna för skydd mot överströmmar skiljer man på överlastströmmar (433) och kortslutningsströmmar (434). Med överlastström menas en överström som normalt beror på ett för stort effektuttag och inte på en kortslutning eller jordfel. När man utelämnar skydd mot överlastström är det just skydd mot ett för stort effektuttag man utelämnar – ledaren kan likväl behöva skydd mot kortslutningsströmmar. Exempel: Elpanna kan vara en belastning och överlastskydd kan utelämnas för matande ledning. Oavsett om ledaren är skyddad mot överlastström ska det alltid kontrolleras att ledarna är skyddade vid kortslutning.
HU: Mit jelent a 433.3-ban említett „túlterhelési védelem kihagyása"? Nem szükséges ilyenkor biztosító?
Magyar: A túlterhelési áramokkal (433) és a rövidzárlatvédőkkel (434) szemben különböző szabályok vonatkoznak. A túlterhelési áromnál normálisan túlzott terhelésvételről van szó, nem rövidzárlatról vagy földhibáról. A túlterhelési védelem kihagyása kizárólag a túlzott terhelésvétel elleni védelmet hagyja ki – a kábelt rövidzárlatnál ettől függetlenül is védeni kell. Példa: Elektromos kazán esetén a túlterhelési védelem elhagyható a tápkábelnél. Ugyanakkor függetlenül attól, hogy a vezető túlterheléssel szemben védett-e, mindig ellenőrizni kell, hogy rövidzárlat esetén is védett-e.

53. kérdés / Fråga 53
SV: Vilken frånkopplingstid gäller för ett uttag med märkström 63 A om fasspänningen, U₀ = 230 V?
Svenska: Automatisk frånkoppling av matningen krävs av två skäl med helt olika villkor. Dels krävs frånkoppling för skydd mot elchock – för en gruppledning med märkström över 32 A får frånkopplingstiden vara högst 5 sekunder (411.3.2.3). Dels krävs frånkoppling av en kortslutning för att kortslutningsströmmen inte ska skada ledarisolering och anslutningar (434.5.2). Denna frånkopplingstid beror på kretsens minsta kortslutningsström, ledararea, isolering och minsta kortslutningsström. (411.3.2 och 434.5.2)
HU: Mekkora kikapcsolási idő érvényes egy 63 A névleges áramú, 230 V fázisfeszültségű konnektornál?
Magyar: Az automatikus leválasztást kétféle okból írják elő, teljesen eltérő feltételekkel. Egyrészt az elektromos ütés elleni védelemhez – 32 A-nél nagyobb névleges áramú csoportvezetéknél a kikapcsolási idő legfeljebb 5 másodperc lehet (411.3.2.3). Másrészt rövidzárlatnál is szükséges a lekapcsolás, hogy a rövidzárlati áram ne károsítsa a vezető szigetelését és a csatlakozásokat (434.5.2). Ez utóbbi kikapcsolási idő a körvezeték minimális rövidzárlati áramától, a vezető keresztmetszetétől és szigetelésétől függ. (411.3.2 és 434.5.2)

54. kérdés / Fråga 54
SV: Vilken area ska det vara på en funktionsutjämningsledare?
Svenska: Det beror på syftet med funktionsutjämningen. Om utjämningen gäller spänningar med normal nätfrekvens anses normalt ledarareor som överensstämmer med fordringarna för kompletterande skyddsutjämning vara tillräckliga (punkt 544.2). Men vid högre frekvenser får istället ledarens längd och utformning en större betydelse. En ledares elektriska motstånd utgörs av resistans, induktans samt kapacitans. Resistansen påverkas av ledarmaterialet, arean och längden – men induktans och kapacitans påverkas inte nämnvärt av arean. Därför måste funktionsutjämningsledare vid högre frekvenser vara så korta som möjligt. (444.5.5)
HU: Mekkora keresztmetszet szükséges a funkcionális kiegyenlítővezetőhöz?
Magyar: Ez a kiegyenlítés céljától függ. Ha a kiegyenlítés normális hálózati frekvencián lévő feszültségekre vonatkozik, a kiegészítő védő kiegyenlítő követelményeivel összhangban lévő vezető keresztmetszetek általában elegendőek (544.2. pont). Magasabb frekvenciákon azonban a vezető hossza és kialakítása válik meghatározóvá. A vezető elektromos ellenállása resistanciából, induktanciából és kapacitásból áll – míg a resistancia befolyásolható a keresztmetszet növelésével, az induktancia és a kapacitás nem. Ezért a funkcionális kiegyenlítővezetőknek a lehető legrövidebbnek kell lenniük magasabb frekvenciákon. (444.5.5)

55. kérdés / Fråga 55
SV: Måste man enligt elinstallationsreglerna installera åsköverspänningsskydd?
Svenska: Fordringarna på skydd mot skada beroende överspänningar orsakade av åska styrs av en riskanalys i elinstallationsreglerna. De samhälleliga konsekvenserna av störningar inom bl.a. sjukhus, publika tjänster, banker, hotell, industrier och lantbruk visar på att skydd mot överspänningar normalt alltid fordras. Men för t.ex. enbostadshus i tätorter visar analysen att man normalt inte behöver något skydd – skydd fordras om d > dₒ. Åskfrekvensen i Sverige är relativt låg med ett snitt på cirka 0,2 nedslag per km² och år, och för en villa i en tätort blir d normalt inte högre än 0,1, vilket medför att några särskilda skyddsåtgärder inte skulle fordras. En modern villa inrymmer dock så mycket elektronik och kommunikationsutrustning att det torde vara oförsvarligt att inte installera skydd, framför allt vid nybyggnation eller större renoveringar. (443.3)
HU: Kötelező-e az elinstallationsreglerna szerint villámtúlfeszültség-védelmet felszerelni?
Magyar: A villámkárok elleni védelmi intézkedések szükségességét kockázatelemzés határozza meg. A kórházak, közszolgáltatások, bankok, szállodák, ipari és mezőgazdasági létesítmények esetén a társadalmi következmények alapján általában mindig szükséges a túlfeszültség elleni védelem. Egylakásos városias házaknál azonban az elemzés általában azt mutatja, hogy nem szükséges különleges védelem – csak ha d > dₒ. Svédországban az ásfrekvencia viszonylag alacsony (kb. 0,2 csapás/km²/év), és egy városi villa esetén a d értéke általában nem haladja meg a 0,1-et, tehát különleges intézkedés általában nem szükséges. Ugyanakkor egy modern ház annyi elektronikát tartalmaz, hogy különösen újépítésnél vagy nagyobb felújításnál célszerű a védelmet felszerelni. (443.3)

`;
